//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class BasicResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BasicResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BasicResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(BasicResult obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~BasicResult() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSHARPSPTAGPINVOKE.delete_BasicResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int VID {
    set {
      CSHARPSPTAGPINVOKE.BasicResult_VID_set(swigCPtr, value);
    } 
    get {
      int ret = CSHARPSPTAGPINVOKE.BasicResult_VID_get(swigCPtr);
      return ret;
    } 
  }

  public float Dist {
    set {
      CSHARPSPTAGPINVOKE.BasicResult_Dist_set(swigCPtr, value);
    } 
    get {
      float ret = CSHARPSPTAGPINVOKE.BasicResult_Dist_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_SPTAG__ByteArray Meta {
    set {
      CSHARPSPTAGPINVOKE.BasicResult_Meta_set(swigCPtr, SWIGTYPE_p_SPTAG__ByteArray.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CSHARPSPTAGPINVOKE.BasicResult_Meta_get(swigCPtr);
      SWIGTYPE_p_SPTAG__ByteArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_SPTAG__ByteArray(cPtr, false);
      return ret;
    } 
  }

  public bool RelaxedMono {
    set {
      CSHARPSPTAGPINVOKE.BasicResult_RelaxedMono_set(swigCPtr, value);
    } 
    get {
      bool ret = CSHARPSPTAGPINVOKE.BasicResult_RelaxedMono_get(swigCPtr);
      return ret;
    } 
  }

  public BasicResult() : this(CSHARPSPTAGPINVOKE.new_BasicResult__SWIG_0(), true) {
  }

  public BasicResult(int p_vid, float p_dist) : this(CSHARPSPTAGPINVOKE.new_BasicResult__SWIG_1(p_vid, p_dist), true) {
  }

  static private global::System.IntPtr SwigConstructBasicResult(int p_vid, float p_dist, byte[] p_meta) {
unsafe { fixed(byte* ptrp_meta = p_meta) { CSHARPSPTAGPINVOKE.WrapperArray tempp_meta = new CSHARPSPTAGPINVOKE.WrapperArray( (System.IntPtr)ptrp_meta, (ulong)p_meta.LongLength );
    return CSHARPSPTAGPINVOKE.new_BasicResult__SWIG_2(p_vid, p_dist,  tempp_meta );
} }
  }

  public BasicResult(int p_vid, float p_dist, byte[] p_meta) : this(BasicResult.SwigConstructBasicResult(p_vid, p_dist, p_meta), true) {
  }

  static private global::System.IntPtr SwigConstructBasicResult(int p_vid, float p_dist, byte[] p_meta, bool p_relaxedMono) {
unsafe { fixed(byte* ptrp_meta = p_meta) { CSHARPSPTAGPINVOKE.WrapperArray tempp_meta = new CSHARPSPTAGPINVOKE.WrapperArray( (System.IntPtr)ptrp_meta, (ulong)p_meta.LongLength );
    return CSHARPSPTAGPINVOKE.new_BasicResult__SWIG_3(p_vid, p_dist,  tempp_meta , p_relaxedMono);
} }
  }

  public BasicResult(int p_vid, float p_dist, byte[] p_meta, bool p_relaxedMono) : this(BasicResult.SwigConstructBasicResult(p_vid, p_dist, p_meta, p_relaxedMono), true) {
  }

}
