//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Edge : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Edge(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Edge obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Edge() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSHARPSPTAGPINVOKE.delete_Edge(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int node {
    set {
      CSHARPSPTAGPINVOKE.Edge_node_set(swigCPtr, value);
    } 
    get {
      int ret = CSHARPSPTAGPINVOKE.Edge_node_get(swigCPtr);
      return ret;
    } 
  }

  public float distance {
    set {
      CSHARPSPTAGPINVOKE.Edge_distance_set(swigCPtr, value);
    } 
    get {
      float ret = CSHARPSPTAGPINVOKE.Edge_distance_get(swigCPtr);
      return ret;
    } 
  }

  public int tonode {
    set {
      CSHARPSPTAGPINVOKE.Edge_tonode_set(swigCPtr, value);
    } 
    get {
      int ret = CSHARPSPTAGPINVOKE.Edge_tonode_get(swigCPtr);
      return ret;
    } 
  }

  public Edge() : this(CSHARPSPTAGPINVOKE.new_Edge(), true) {
  }

}
