//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class NodeDistPair : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal NodeDistPair(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(NodeDistPair obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~NodeDistPair() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CSHARPSPTAGPINVOKE.delete_NodeDistPair(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int node {
    set {
      CSHARPSPTAGPINVOKE.NodeDistPair_node_set(swigCPtr, value);
    } 
    get {
      int ret = CSHARPSPTAGPINVOKE.NodeDistPair_node_get(swigCPtr);
      return ret;
    } 
  }

  public float distance {
    set {
      CSHARPSPTAGPINVOKE.NodeDistPair_distance_set(swigCPtr, value);
    } 
    get {
      float ret = CSHARPSPTAGPINVOKE.NodeDistPair_distance_get(swigCPtr);
      return ret;
    } 
  }

  public NodeDistPair(int _node, float _distance) : this(CSHARPSPTAGPINVOKE.new_NodeDistPair__SWIG_0(_node, _distance), true) {
  }

  public NodeDistPair(int _node) : this(CSHARPSPTAGPINVOKE.new_NodeDistPair__SWIG_1(_node), true) {
  }

  public NodeDistPair() : this(CSHARPSPTAGPINVOKE.new_NodeDistPair__SWIG_2(), true) {
  }

}
