//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ResultIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnBase;

  internal ResultIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwnBase = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ResultIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ResultIterator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnBase) {
          swigCMemOwnBase = false;
          CSHARPSPTAGPINVOKE.delete_ResultIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ResultIterator(global::System.IntPtr p_index, global::System.IntPtr p_target, bool p_searchDeleted, int p_workspaceBatch) : this(CSHARPSPTAGPINVOKE.new_ResultIterator(p_index, p_target, p_searchDeleted, p_workspaceBatch), true) {
  }

  public global::System.IntPtr GetWorkSpace() {
    global::System.IntPtr ret = CSHARPSPTAGPINVOKE.ResultIterator_GetWorkSpace(swigCPtr);
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual BasicResult[] Next(int batch) {
    CSHARPSPTAGPINVOKE.WrapperArray data = CSHARPSPTAGPINVOKE.ResultIterator_Next(swigCPtr, batch);
    BasicResult[] ret = new BasicResult[data._size];
    System.IntPtr ptr = data._data;
    for (ulong i = 0; i < data._size; i++) {
        CSHARPSPTAGPINVOKE.WrapperArray arr = (CSHARPSPTAGPINVOKE.WrapperArray)System.Runtime.InteropServices.Marshal.PtrToStructure(ptr, typeof(CSHARPSPTAGPINVOKE.WrapperArray));
        ret[i] = new BasicResult(arr._data, true);
        ptr += sizeof(CSHARPSPTAGPINVOKE.WrapperArray);
    }
    CSHARPSPTAGPINVOKE.deleteArrayOfWrapperArray(data._data);
    
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
    return ret;
}

  public virtual bool GetRelaxedMono() {
    bool ret = CSHARPSPTAGPINVOKE.ResultIterator_GetRelaxedMono(swigCPtr);
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_SPTAG__ErrorCode GetErrorCode() {
    SWIGTYPE_p_SPTAG__ErrorCode ret = new SWIGTYPE_p_SPTAG__ErrorCode(CSHARPSPTAGPINVOKE.ResultIterator_GetErrorCode(swigCPtr), true);
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Close() {
    CSHARPSPTAGPINVOKE.ResultIterator_Close(swigCPtr);
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
  }

  public global::System.IntPtr GetTarget() {
    global::System.IntPtr ret = CSHARPSPTAGPINVOKE.ResultIterator_GetTarget(swigCPtr);
    if (CSHARPSPTAGPINVOKE.SWIGPendingException.Pending) throw CSHARPSPTAGPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
