experimentName: sift128
trialConcurrency: 4
maxExperimentDuration: 168h
searchSpaceFile: search_space.json
trialCommand: python main.py --train_file sift-128-euclidean.hdf5

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService: 
  platform: local

